apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::616532015738:role/main-eks-node-group-20231028074046119500000001
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::616532015738:user/kitakyusyu-17
      username: kitakyusyu-17
      groups:
        - system:masters
